config/routes.rb
Lyks::Application.routes.draw do

  resources :lyks

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/lyk.rb
class Lyk < ActiveRecord::Base
  attr_accessible :description, :image
  validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence:true,
																content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif']}

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :lyks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lyks_controller.rb
class LyksController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  # GET /lyks
  # GET /lyks.json
  def index
    @lyks = Lyk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lyks }
    end
  end

  # GET /lyks/1
  # GET /lyks/1.json
  def show
    @lyk = Lyk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lyk }
    end
  end

  # GET /lyks/new
  # GET /lyks/new.json
  def new
    @lyk = current_user.lyks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lyk }
    end
  end

  # GET /lyks/1/edit
  def edit
    @lyk = current_user.lyks.find(params[:id])
  end

  # POST /lyks
  # POST /lyks.json
  def create
    @lyk = current_user.lyks.new(params[:lyk])

    respond_to do |format|
      if @lyk.save
        format.html { redirect_to @lyk, notice: 'Lyk was successfully created.' }
        format.json { render json: @lyk, status: :created, location: @lyk }
      else
        format.html { render action: "new" }
        format.json { render json: @lyk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lyks/1
  # PUT /lyks/1.json
  def update
    @lyk = current_user.lyks.find(params[:id])

    respond_to do |format|
      if @lyk.update_attributes(params[:lyk])
        format.html { redirect_to @lyk, notice: 'Lyk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lyk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lyks/1
  # DELETE /lyks/1.json
  def destroy
    @lyk = current_user.lyks.find(params[:id])
    @lyk.destroy

    respond_to do |format|
      format.html { redirect_to lyks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyks_helper.rb
module LyksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "David Spotts", "http://davidspotts.com" %>
    by <%= link_to "AEQU", "http://aequ.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand">Lyks.it</a>
    <ul class="nav">
      <li>
      </li>
      <li>
        <%= link_to 'Home',  root_path %>
      </li>
      <li>
        <%= link_to 'About',  about_path %>
      </li>
    </ul>
    
    <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout',  destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile',  edit_user_registration_path %></li>
          <% else %>
          <li><%= link_to 'Login',  new_user_session_path %></li>
          <% end %>
          
    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lyks.it</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <%= render 'layouts/header' %>
    </div>    
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}" ) %>
        <% end -%>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  
  </body>
</html>

app/views/lyks/_form.html.erb
<%= simple_form_for(@lyk, html: {class:"form_horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_file_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload and Image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" }  %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lyks/_lyk.html.erb
<tr>
	  <td><%= image_tag lyk.image(:medium) %></td>
    <td><%= lyk.description %></td>
    <% if current_user == lyk.user %>
    <td><%= link_to 'Show', lyk %></td>
    <% end %>
    <td><%= link_to 'Edit', edit_lyk_path(lyk) %></td>
    <td><%= link_to 'Destroy', lyk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/lyks/edit.html.erb
<h1>Editing lyk</h1>

<%= render 'form' %>

<%= link_to 'Show', @lyk %> |
<%= link_to 'Back', lyks_path %>

app/views/lyks/index.html.erb
<h1>Lyk Stream</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <%= render @lyks %>
    </tbody>
</table>

<br />

<%= link_to 'New Lyk', new_lyk_path %>

app/views/lyks/new.html.erb
<h1>New Lyk</h1>

<%= render 'form' %>

<%= link_to 'Back', lyks_path %>

app/views/lyks/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
  		<b>Description:</b>
      <%= image_tag @lyk.image %>
  		<%= @lyk.description %>
  		</p>
  		<p>
  		<%= @lyk.user.name %>
  		</p>
      <% if current_user == @lyk.user %>
      <%= link_to 'Edit', edit_lyk_path(@lyk) %> |
      <% end %>
      <%= link_to 'Back', lyks_path %>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "One Month Rails", "http://onemonthrails.com" %>
  is a project to teach 
  <%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
  in one month. This is the sample application.
</p>

app/views/pages/home.html.erb
<div class="hero-unit">

<h1>Welcome to Lyks.it</h1>
<p>
  All the stuff you like from sites like Twitter, Flickr and Instagram in one place.
  An <%= link_to "aequ", "http://aequ.com" %>
  application.
</p>
<p>
  <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
</p>
</div>